### PR TITLE
First mocha test

### PR DESCRIPTION
**Pull request by phbernard**
Hi Hayden,

I finally wrote the first test! It's very minimalist but I think it paves the way for a comprehensive, yet manageable test suite.

Long story short: I added a "Contributing" section to the Readme which explains how to add a new test case. You would review this and let me know if that's okay?

As an aside: currently the test can fail because the order of the HTML markups is not always the same. This can be changed easily, so testability is not a concern. But some end users might be surprised by this behavior.

### CODE REVIEW

**Comment by haydenbleasel** [comment]
Look good mate, we can work on expanding this together!

**Comment by phbernard** [comment]
Great! Do you want to integrate first, and then I can rebase and start coding some more tests?

**Comment by haydenbleasel** [comment]
Yep I'm just setting up my local stuff now, installed mocha globally and changed the test script to `mocha test/favicons.js` but it's immediately throwing errors so I'll need to solve them first e.g. 

```
> mocha test/favicons.js



  Favicon local generation
    1) should generate a favicon only for desktop browsers


  0 passing (1s)
  1 failing

  1) Favicon local generation should generate a favicon only for desktop browsers:
     Uncaught Error: ENOENT: no such file or directory, scandir 'test/expected/favicons/desktop_only/files'
      at Error (native)
      at Object.fs.readdirSync (fs.js:813:18)
      at assertAnyFiles (test/test.js:33:21)
      at assertFiles (test/test.js:58:3)
      at Object.assertFaviconGeneration (test/test.js:65:5)
      at test/favicons.js:28:12
      at index.js:141:13
      at node_modules/async/lib/async.js:52:16
      at node_modules/async/lib/async.js:1204:30
      at index.js:136:21
      at index.js:127:21
      at index.js:95:17
      at node_modules/async/lib/async.js:52:16
      at done (node_modules/async/lib/async.js:246:17)
      at node_modules/async/lib/async.js:44:16
      at index.js:89:32
      at index.js:78:17
      at node_modules/async/lib/async.js:721:13
      at node_modules/async/lib/async.js:52:16
      at done (node_modules/async/lib/async.js:246:17)
      at node_modules/async/lib/async.js:44:16
      at node_modules/async/lib/async.js:718:17
      at node_modules/async/lib/async.js:167:37
      at index.js:70:25
      at index.js:63:17
      at node_modules/async/lib/async.js:52:16
      at done (node_modules/async/lib/async.js:246:17)
      at node_modules/async/lib/async.js:44:16
      at index.js:61:21
      at index.js:36:17
      at node_modules/async/lib/async.js:52:16
      at node_modules/async/lib/async.js:1204:30
      at index.js:34:25
      at Jimp.<anonymous> (helpers.js:174:32)
      at node_modules/jimp/index.js:1545:27
      at node_modules/jimp/node_modules/stream-to-buffer/node_modules/stream-to/index.js:39:7
      at onEnd (node_modules/jimp/node_modules/stream-to-buffer/node_modules/stream-to/index.js:18:5)
      at null.<anonymous> (node_modules/jimp/node_modules/pngjs/lib/packer.js:66:10)
      at endReadableNT (_stream_readable.js:903:12)



npm ERR! Test failed.  See above for more details.
```

These unit tests are going to be used by Travis so gotta be validated :D

**Comment by phbernard** [comment]
Ok I get it. Git didn't take this empty directory into account (there is no file for this test case so `files` is empty). I'm going to update the mini-framework to take this case into account.

**Comment by haydenbleasel** [comment]
Ahhh okay, don't worry I'll fix that up with mkdirp.

**Comment by phbernard** [comment]
Too late, it's fixed in my side :)

**Comment by haydenbleasel** [comment]
Hahaha okay no worries. We can bring that in next PR with the new test :)

**Comment by phbernard** [comment]
Yep! I'm going to write a few test cases and port the existing tests for the RFG's API.

**Comment by haydenbleasel** [comment]
Sounds good mate :+1:

**Pull request merged**
