### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by markmiro**
src option does not allow multiple images because to do so RFG would have to do it and it doesn't. I spent a lot of time trying to figure out why this wasn't working until I figured out that the feature is not supported. Let's keep this out of the documentation until it gets fixed.

### CODE REVIEW

**Comment by haydenbleasel** [comment]
Yep good call. Might want to fix the following line in the same request:

```
src: null,                // Path for file to produce the favicons. `string` or `object`
```

`2.x.x` doesn't accept an object yet I think. Nightmare getting this sorted :/

**Comment by markmiro** [comment]
You're right. I updated the readme

**Comment by haydenbleasel** [comment]
Awesome, thanks so much. Sorry about this bad maintenance, we're currently re-working the whole RFG / Favicons architecture so some bits and pieces are off.

**Comment by markmiro** [comment]
No worries. You're pretty fast to respond to this stuff

**Comment by haydenbleasel** [comment]
University holidays :) Just hammering away at open source code basically.

**Pull request merged**
