### PR TITLE
Expose config.

### PR DESCRIPTION
**Pull request by adjohnson916**
Expose config so consumers of the module can programmatically get a list of files generated without having to read the `config/icons.json` file themselves.
Wanted for https://github.com/davewasmer/ember-cli-favicon/issues/5.

If you prefer, we can expose a deep clone of the config, so that modification isn't possible - though for that, we might want to upgrade from `underscore` to `lodash`.

If you're open to it, I want to go even further and expose a flattened list of files, e.g.:
```js
modules.exports.files = ['favicon.png'].concat(_(config.icons).map(function (icon) {
  return Object.keys(icon);
}).flatten().value());
```
Let me know and I can add that to this PR before you merge.

### CODE REVIEW

**Comment by haydenbleasel** [comment]
I can see the value in this. I also like how neat `module.exports.config = config;` is at the moment. Can you add something to the readme to let people know about this new export? Not sure about `.files` just yet, it feels a bit messy but we should find a good way of listing these files for sure.

**Comment by adjohnson916** [comment]
@haydenbleasel Thanks, I've pushed another commit that adds the info to the README - is that what you were thinking?

**Comment by haydenbleasel** [comment]
Yep cool :+1:

**Comment by adjohnson916** [comment]
@haydenbleasel Thanks, any idea when there will be a next release to include this?

**Comment by haydenbleasel** [comment]
@adjohnson916 It's in the `4.4.5` tag (available now) and it'll be in the `4.5.0` official release.

**Comment by adjohnson916** [comment]
@haydenbleasel Oh thanks. I didn't see that. Do you not always push the tags to GitHub?

**Comment by haydenbleasel** [comment]
@adjohnson916 I create a new release manually every minor update. There's always a handful of patches and fixes per tag / release so sometimes you'll have to wait a little bit.

**Pull request merged**
