### PR TITLE
Remove out-of-place android icon from "favicon" list

### PR DESCRIPTION
**Pull request by kb3eua**

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@kb3eua why? need proof link

**Comment by kb3eua** [comment]
@evilebottnawi Because no file is being generated for the <link> element that's inserted into markup for the android icon, and other icons are generated but <link> elements for them are never inserted into the markup.  This change helps bring what's generated and what's linked into alignment.  Note that I'm only using the setting "favicon: true" here... I've set all other vendor-specific icons to "false", so I wouldn't expect to get an android icon when I have "android: false".

**Comment by evilebottnawi** [comment]
@kb3eua 96x96 and 230x230 is not `android` specific images, some browsers with high resolution monitor request this sizes

**Comment by evilebottnawi** [comment]
@kb3eua favicon.ico used only ms and old other browser, new generation browsers gets favicon.png with 96px, very new generation browser gets favicons.png with 230px

**Comment by kb3eua** [comment]
@evilebottnawi I don't think you're understanding the issue.  The file "icons.json" defines what files are created, while "html.json" defines what links are injected into the HTML page.

The 96x96 and 230x230 icons defined in "icons.json" had no corresponding links defined in "html.json", so generating them was pointless since there was never any link generated for the user to download them.

Conversely, "html.json" had a link to the file "android-chrome-192x192.png" (which is android specific), a file which is not defined in "icons.json" and therefore is never created, resulting in 404 errors when the browser attempts to download it.

**Comment by oomathias** [comment]
@haydenbleasel Could you release a new version with these changes?

**Pull request merged**
